server.port=8088
server.context-path=/cm

# mysql数据库配置（腾讯云）
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://140.143.12.237:3306/cloud_memory?useSSL=false&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
spring.datasource.username=root
spring.datasource.password=Wang_1001

# redis缓存配置（王子湉的开发机）
spring.redis.host=10.20.69.35
spring.redis.port=6379



# 开放所有的Web Endpoint
management.endpoints.web.exposure.include=*

# Feign测试
rest.feign.test.url=http://localhost:8082

